# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        # Don't fail CI on coverage drops for now
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "**/tests/**"
  - "**/benches/**"
  - "crates/bindings/python/**"  # Python bindings are integration-tested separately
